### PR TITLE
359-session-data-comes-back-encoded

### LINKED ISSUE #359: Session data comes back encoded from auth-helpers-sveltekit when using OAuth with Google
# Bug report

When using `signInWithOAuth` with `auth-helpers-sveltekit`, user data in session is encoded.

## Describe the bug

For example, the following login

```js
	const { error } = await supabaseClient.auth.signInWithOAuth({
		provider: 'google',
		options: { redirectTo: window.location.origin }
	})
```

returns a user 
```json
{
    "id": "95ae3b97-308b-48d0-b6a8-ca4cecc1c734",
    "aud": "authenticated",
    "email": "ales@vaupotic.eu",
    "phone": "",
    "app_metadata": {
        "provider": "google",
        "providers": [
            "google"
        ]
    },
    "user_metadata": {
        "avatar_url": "https://lh3.googleusercontent.com/a/ALm5wu0gqKlOGLtZN5A0CTOzfmAO8rnd-v0cMjLPzboU1w=s96-c",
        "email": "ales@vaupotic.eu",
        "email_verified": true,
        "full_name": "AleÅ¡ VaupotiÄ",
        "iss": "https://www.googleapis.com/userinfo/v2/me",
        "name": "AleÅ¡ VaupotiÄ",
        "picture": "https://lh3.googleusercontent.com/a/ALm5wu0gqKlOGLtZN5A0CTOzfmAO8rnd-v0cMjLPzboU1w=s96-c",
        "provider_id": "114084102336688010361",
        "sub": "114084102336688010361",
        "test5": "updated",
        "theme": "sedem"
    },
    "role": "authenticated",
    "session_id": "514cb785-6282-4a1f-a0a6-019fc4eb824a"
}

```

## To Reproduce

1. Clone the repo at https://github.com/alesvaupotic/sveltekit-user-management-encoding which is adapted from example
2. Fill `.env` with your credentials
3. Follow https://supabase.com/docs/guides/auth/auth-google to set up Google Auth
4. `pnpm install`
5. `pnpm run dev`
6. Login with your Google Account
7. Check the results on screen or in console

## Expected behavior

AleÅ¡ VaupotiÄ� should read Aleš Vaupotič

## Screenshots

image

## System information

```
 System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
    Memory: 1.22 GB / 7.90 GB
  Binaries:
    Node: 18.9.1 - C:\Program Files\nodejs\node.EXE
    npm: C:\Users\ales\code\_reepolee-labs_\sveltekit-user-management-encoding>pnpm -v     
7.14.1 - C:\bat\npm.BAT
  Browsers:
    Chrome: 107.0.5304.63
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.26)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @fontsource/fira-mono: ^4.5.0 => 4.5.10
    @neoconfetti/svelte: ^1.0.0 => 1.0.0
    @supabase/auth-helpers-sveltekit: ^0.8.3 => 0.8.5
    @supabase/supabase-js: ^2.0.4 => 2.0.5
    @sveltejs/adapter-auto: next => 1.0.0-next.86
    @sveltejs/kit: next => 1.0.0-next.531
    @types/cookie: ^0.5.1 => 0.5.1
    prettier: ^2.6.2 => 2.7.1
    prettier-plugin-svelte: ^2.7.0 => 2.8.0
    svelte: ^3.46.0 => 3.52.0
    svelte-check: ^2.7.1 => 2.9.2
    svelte-preprocess: ^4.10.6 => 4.10.7
    tslib: ^2.3.1 => 2.4.1
    typescript: ^4.7.4 => 4.8.4
    vite: ^3.1.0 => 3.2.2

```

## Additional context

Session comes back fine when using regular `supabase-js`. The Sveltkit implementation (or some shared lib) encodes the data.

### PR DESCRIPTION
**Pull request by supastore**
## What kind of change does this PR introduce?

Fixes [the unicode problem](https://developer.mozilla.org/en-US/docs/Glossary/Base64#the_unicode_problem) by converting the string to percent-encoding before being decoded

Note: the escape function is obsolete, which is why i went with this fix

## What is the current behavior?

The atob function cannot decode chars outside the latin1 range

## What is the new behavior?
characters outside the latin1 range can be decoded

fixes #359

### CODE REVIEW

**Comment by thorwebdev** [comment]
@supastore thanks so much for looking into this. Could you outline the sources you used to come to this solution? It works, but I'd love to understand the background. Thanks :)

**Comment by thorwebdev** [comment]
Ah, I think I found it: https://stackoverflow.com/a/30106551/17622044

image

Great, thanks.

File: packages/shared/src/utils/cookies.ts [hunk 1]
```diff
@@ -51,7 +51,13 @@ const decodeBase64URL = (value: string): string => {
     // but if it is not it will throw a ReferenceError in which case we can try to use Buffer
     // replace are here to convert the Base64-URL into Base64 which is what atob supports
     // replace with //g regex acts like replaceAll
-    return atob(value.replace(/[-]/g, '+').replace(/[_]/g, '/'));
+    // map first encodes the string to percent-encoding before being decoded
```
Comment (thorwebdev) [inline packages/shared/src/utils/cookies.ts:54]:
```suggestion
    // Decoding base64 to UTF8 see https://stackoverflow.com/a/30106551/17622044
```

**Review by thorwebdev — APPROVED** [review]
LGTM, thanks you 💚
